# Generated by Django 6.0.1 on 2026-03-22 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('source', models.CharField(help_text='e.g., templatemo-530', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(choices=[('minimal', 'Minimal'), ('dark', 'Dark'), ('glassmorphism', 'Glassmorphism'), ('gradient', 'Gradient'), ('colorful', 'Colorful'), ('professional', 'Professional')], default='minimal', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSelectedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizations', models.JSONField(default=dict)),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_design.designtemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_template', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Selected Template',
                'verbose_name_plural': 'User Selected Templates',
            },
        ),
    ]
