# Generated by Django 5.0.6 on 2025-02-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
