# Generated by Django 5.0.6 on 2025-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
