# Generated by Django 5.0.6 on 2025-02-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_educationdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationentry',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='educationentry',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='educationentry',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
