# Generated by Django 6.0.1 on 2026-03-15 17:05

import education.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_educationentry_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdesign',
            name='design_config',
            field=models.JSONField(blank=True, default=education.models.default_education_design_config, null=True),
        ),
    ]
