# Generated by Django 6.0.1 on 2026-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_educationdesign_design_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationentry',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='educationentry',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
