# Generated by Django 5.0.6 on 2025-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Name', max_length=200)),
                ('description', models.TextField(default='Bio Descriptions')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='backgrounds/')),
                ('youtube_link', models.URLField(default='https://www.youtube.com/')),
                ('linkedin_link', models.URLField(default='https://www.linkedin.com/')),
                ('facebook_link', models.URLField(default='https://www.facebook.com/')),
                ('twitter_link', models.URLField(default='https://x.com/')),
            ],
        ),
    ]
