# Generated by Django 5.0.6 on 2025-02-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagecontent_is_published_homepagecontent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='custom_settings',
            field=models.JSONField(default=dict),
        ),
    ]
