# Generated by Django 5.0.6 on 2025-02-13 14:00

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagecontent_custom_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='custom_settings',
            field=models.JSONField(default=home.models.default_custom_settings),
        ),
    ]
