# Generated by Django 6.0.1 on 2026-03-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepagecontent_custom_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
