# Generated by Django 6.0.1 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_add_defaults_to_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
    ]
