# Generated by Django 6.0.1 on 2026-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_resume',
            field=models.FileField(blank=True, null=True, upload_to='profiles/resumes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_resume_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
