# Generated by Django 6.0.1 on 2026-03-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profilenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_template',
            field=models.CharField(blank=True, default='professional', max_length=50),
        ),
    ]
