# Generated by Django 6.0.1 on 2026-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_add_visibility_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
