# Generated by Django 6.0.1 on 2026-03-24 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Custom domain (e.g., portfolio.johnsmith.com)', max_length=255, unique=True)),
                ('verification_token', models.CharField(default=uuid.uuid4, help_text='Token for TXT record verification', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'DNS Verified'), ('ssl_pending', 'SSL Pending'), ('active', 'Active'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('dns_verified', models.BooleanField(default=False)),
                ('ssl_provisioned', models.BooleanField(default=False)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('verification_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
            },
        ),
    ]
