# Generated by Django 5.0.6 on 2025-02-14 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDesignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_width', models.IntegerField(default=350)),
                ('card_height', models.IntegerField(default=180)),
                ('font_size', models.IntegerField(default=16)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('borderColor', models.CharField(default='#000000', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
