# Generated by Django 5.0.6 on 2025-02-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
