# Generated by Django 6.0.1 on 2026-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerentry',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
