# Generated by Django 6.0.1 on 2026-03-15 17:05

import career.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdesignsettings',
            name='design_config',
            field=models.JSONField(blank=True, default=career.models.default_career_design_config, null=True),
        ),
    ]
