# Generated by Django 6.0.1 on 2026-03-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_alter_careerentry_options_careerentry_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', '-proficiency']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('tools', 'Tools & Software'), ('design', 'Design'), ('database', 'Database'), ('cloud', 'Cloud & DevOps'), ('soft_skills', 'Soft Skills'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=50, help_text='Skill proficiency level (0-100)'),
        ),
    ]
