# Generated by Django 5.0.6 on 2025-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertabsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
